# Generated by Django 5.2.4 on 2025-07-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('filterered_image', models.ImageField(blank=True, null=True, upload_to='filtered/')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
