# Generated by Django 5.2.4 on 2025-07-23 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qrcode',
            old_name='deta',
            new_name='data',
        ),
    ]
